version: '3.7'

services:
  geomatys-frontend:
    container_name: frontend
    build: ./
    working_dir: /usr/src/app
    command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
  geomatys-backend:
    container_name: backend
    build: ../geomatys_api
    ports:
      - "8080:8080"      